---
openapi: 3.0.0
info:
  version: 2.0.0
  description: "This is an API description of the HTTPPool Server for FDI (Flexible\
    \ Dataset Integrator)"
  title: "fdi poolserver"
  contact:
    email: "mhuang@nao.syx1026-qq.com"
  license:
    name: "LGPL 3.0"
servers:
  - url: http://127.0.0.1:5000/v0.8

security:
  - BasicAuth: []

paths:
  /:
    get:
      summary: "Get IDs of all registered Pools."
      description: "Returns a list of Pool IDs (pool names) of all poolson registered with the Global PoolManager."
      operationId: "get_poolmanager"
      responses:
        "200":
          description: "Done getting all ID of registered Pools."
          content:
            $ref: '#/components/schemas/responseContents1'

# Descriptions of common components
components:
  # Basic authentication
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  parameters:
    PoolId:
      name: "poolid"
      in: "path"
      description: "pool ID (also called pool name)"
      required: true
      schema:
        type: "string"

    # Schema for response body
  schemas:
    responseContents1:
      application/json:
        schema:
          type: object 
          properties:
            code:
              type: string
            result:
              type: string
            msg:
              type: string
            time:
              type: "number"
              format: "double"
    responseContents:
      content:
        application/json:
          schema:
            type: object 
            properties:
              code:
                type: string
              result:
                type: string
              msg:
                type: string
              time:
                type: "number"
                format: "double"
            required:
              - code
              - result
              - msg
              - time
            example:
              code: "200"
              result: "[7.8, \"foo\"]"
              msg: "pool is deleted"
              time: 15948800582498.8613281
  
    errorResponses:
      content:
        application/json:
          schema:
            type: object 
            properties:
              "400":
                $ref: '#/components/responses/400Error'
              "401":
                $ref: '#/components/responses/401Error'
              "404":
                $ref: '#/components/responses/404Error'
              "409":
                $ref: '#/components/responses/409Error'
              default:
                $ref: '#/components/responses/defaultError'
      
  responses:
    400Error:
      allOf:
      - description: Fails. Invalid request. poolID does not exist.
      - $ref: '#/components/schemas/responseContents'
    401Error:
      allOf:
      - description: Fails. Authorization information is missing or invalid.
      - $ref: '#/components/schemas/responseContents'
    404Error:
      allOf:
      - description: Fails. User with the specified ID was not found.
      - $ref: '#/components/schemas/responseContents'
    409Error:
      allOf:
      - description: Fails. Unavailable. Pool is busy at the moment.
      - $ref: '#/components/schemas/responseContents'
    defaultError:
      allOf:
      - description: Fails. Other errors.
      - $ref: '#/components/schemas/responseContents'
      
