version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: {{cookiecutter.project_name}}:latest
    env_file:
      - .env
    environment:
      - {{cookiecutter.project_name | upper }}_HOST=0.0.0.0

  {%- if cookiecutter.db_info.name == "postgresql" %}
  db:
    image: postgres:13.4-buster
    hostname: {{cookiecutter.project_name}}-db
    environment:
      - POSTGRES_PASSWORD={{cookiecutter.project_name}}
      - POSTGRES_USER={{cookiecutter.project_name}}
      - POSTGRES_DB={{cookiecutter.project_name}}
    volumes:
      - {{cookiecutter.project_name}}-db-data:/var/lib/postgresql/data
  {%- endif %}

  {%- if cookiecutter.db_info.name == "mysql" %}
  db:
    image: bitnami/mysql:8.0.26
    hostname: {{cookiecutter.project_name}}-db
    environment:
      - MYSQL_PASSWORD={{cookiecutter.project_name}}
      - MYSQL_USER={{cookiecutter.project_name}}
      - MYSQL_DATABASE={{cookiecutter.project_name}}
    volumes:
      - {{cookiecutter.project_name}}-db-data:/bitnami/mysql/data
  {%- endif %}

  {% if cookiecutter.db_info.name != 'none' %}
  migrator:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: {{cookiecutter.project_name}}:latest
    command: wait-for-it {{cookiecutter.project_name}}-db:{{cookiecutter.db_info.port}} -- alembic upgrade head
  {%- endif %}

  {%- if cookiecutter.enable_redis == "True" %}
  redis:
    image: bitnami/redis:6.2.5
    hostname: {{cookiecutter.project_name}}-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  {%- endif %}

{% if cookiecutter.db_info.name != 'none' %}
volumes:
  {{cookiecutter.project_name}}-db-data:
    name: {{cookiecutter.project_name}}-db-data
{% endif %}
