model_config:
    hidden_dims: [32, 32]
    normal_std: 0.1
dataset_config:
    env_name: "LunarLander-v2"
    max_env_steps: 10000
    gamma: 0.99
    discount_rewards: true
    normalize_rewards: true
    random_policy: false
    num_rollouts: 100
    num_workers: 5
optimizer_config:
    lr: 0.002
logging_config:
    checkpoint_interval: 10