
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-22T10:43:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8402be870b8a89aff0286107ff88c57273b6b02d",
 "version": "v0.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
