[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aws_custom_ews_kafka_resources"
version = "0.2.0"
description = "Custom Resources for AWS CloudFormation representing Kafka assets management"
authors = ["John Preston <john@ews-network.net>"]
license = "MPL-2.0"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
readme = "README.rst"
include = [
    "LICENSE",
    "NOTICES.rst"
]

[tool.poetry.dependencies]
python = "^3.7"
troposphere = "^3.0"
tbump = "6.3.1"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.3"
Sphinx = "^4.1"
sphinx-material = "^0.0.34"
pre-commit = "^2.14.0"
placebo = "^0.9.0"
coverage = "^5.5"
pytest = "^6.2.4"
flake8 = "^3.9.2"
tox = "^3.24.3"
tbump = "6.3.1"
twine = "^3.4.2"

[tool.tbump]
github_url = "https://github.com/EWS-Network/aws_custom_ews_kafka_resources.git"

[tool.tbump.version]
current = "0.2.0"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "pyproject.toml"

[[tool.tbump.file]]
src = "aws_custom_ews_kafka_resources/__init__.py"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = "kelvin"

[tool.coverage.report]
exclude_lines = [
    "if __name__ == '__main__'"
]
[tool.coverage.run]
omit = [
    "*/cli.py"
]
