[tool.poetry]
name = "arductl"
version = "0.1.0b"
description = "Helper Library to execute ArduPilot simulations using a Docker Container and dronekit."
authors = ["Aniruddh Chandratre <achand75@asu.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
dronekit = "^2.9.2"
numpy = "^1.20.3"
MAVProxy = "^1.8.38"
pydantic = "^1.8.2"
docker = "^5.0.0"
dronekit-sitl = "^3.3.0"
pymavlink = "2.4.8"
attrs = "^21.0.0"
cattrs = "^1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
