[tool.poetry]
name = "madr"
version = "0.0.1"
description = "A comprehensive toolset around making and managing MADRs using source control"
authors = ["WilliamJohns <will@wcj.dev>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
