[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "999"

[tool.pytest.ini_options]
addopts = '--doctest-modules --ignore=noxfile.py -n=auto -v --cov=pygeoutils --cov-report xml --durations=5'
