# coding: utf-8

"""
    Dockstore API

    This describes the dockstore API, a webservice that manages pairs of Docker images and associated metadata such as CWL documents and Dockerfiles used to build those images. Explore swagger.json for a Swagger 2.0 description of our API and explore openapi.yaml for OpenAPI 3.0 descriptions.  # noqa: E501

    OpenAPI spec version: 1.12.0-alpha.1-SNAPSHOT
    Contact: theglobalalliance@genomicsandhealth.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jgreenepack
from jgreenepack.jgreenepack.api.tool_tester_api import ToolTesterApi  # noqa: E501
from jgreenepack.rest import ApiException


class TestToolTesterApi(unittest.TestCase):
    """ToolTesterApi unit test stubs"""

    def setUp(self):
        self.api = jgreenepack.jgreenepack.api.tool_tester_api.ToolTesterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tool_tester_log(self):
        """Test case for get_tool_tester_log

        """
        pass

    def test_search(self):
        """Test case for search

        """
        pass


if __name__ == '__main__':
    unittest.main()
