VERSION_YEAR = 2021
VERSION_MONTH = int('08')
VERSION_DAY = int('26')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('26')
MAJOR_VERSION = 0
MINOR_VERSION = 2
PATCH_VERSION = 202108260926
version_date = '2021/08/26 09:26'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
