
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-27T18:09:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "15f106b8d14cbc893415c2eeb4b439bcf6cdefa0",
 "version": "0.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
