[tool.poetry]
name = "paloalto_env"
version = "0.1.7"
description = "Palo Alto Env wrapper"
authors = ["Thomas Christory"]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = ">=0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
