[tool.poetry]
name = "timing-asgi-statsd"
packages = [
    {include = "timing_asgi"},
]
version = "0.4.0"
description = "ASGI middleware to emit timing metrics with something like statsd"
authors = ["Nikita Konin <awesome@nkonin.me>", "Steinn Eldjárn Sigurðarson <steinnes@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
alog = "^0.9.13"

[tool.poetry.dev-dependencies]
starlette = "^0.12.0"
pytest = "^4.3"
pytest-cov = "^2.6"
requests = "^2.21"
pytest-asyncio = "^0.10.0"
asynctest = "^0.12.2"
flake8 = "^3.7"
black = {version = "^20.8b1", allow-prereleases = true}
twine = "^3.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
