NAMES = [
  "Chuckie",
  "Spunky",
  "Bucko",
  "Fucko",
  "Buddy",
  "Buster",
  "Biff",
  "Slick"
]

QUOTES = [
  "C'mon in!",
  "FUNHOUSE? A ha ha ha ha ha ha!!!!!",
  "Ya ain't seen the likes of me!",
  "Howdy, {name}",
  "Hey {name}",
  "Hey!",
  "Hey {name}, you can have it back!",
  "Hey {name}, you're up!",
  "How was that?",
  "Gangway!",
  "Frenzy! A ha ha ha ha ha ha!!!!",
  "Big points!!!",
  "Hey, {name}, you stole the show!",
  "Great shot!",
  "Nice going!",
  "Hey {name}, there's an extra ball!",
  "Hey {name}, shoot again!",
  "I feel like a million!",
  "Let's play two!",
  "Zoom!",
  "It's lunchtime! Get yourself a hot dog!",
  "Yum yum!",
  "I'm still hungry!",
  "I'm not hungry.",
  "Hey, {name}, go play on the steps!",
  "Maybe next time.",
  "You missed again!",
  "Now who's the dummy?",
  "Owww!!!!",
  "Gulp! Ptooey!",
  "Hey, it's only pinball!",
  "This is really starting to annoy me.",
  "What did I ever do to you?",
  "Big deal!",
  "You....big.....m....sausage!",
  "Here it comes {name}!",
  "Right back at ya {name}!",
  "Look out {name}!",
  "Where did you go now?",
  "Hey, {name}, the door's open.",
  "No way!",
  "Heh heh heh.",
  "It's getting late",
  "Stay away from the clock.",
  "I'm not happy with you now.",
  "You're making me very unhappy.",
  "I thought we were pals.",
  "That was no accident!",
  "Quit playing with the clock!",
  "Oh no. (Yawn) I'm sleepy. (Yawn) (Yawn) (Snore...............)" ,
  "Gulp. MMMmmmm. Hmmhmhmhmh. MMMMMMMMM BLEGCH!!!!",
  "Stay away from that door!",
  "Stop running around!",
  "You don't know what's in there!",
  "You don't wanna go down there!",
  "Don't go near the door!",
  "Hey! Close the door!",
  "Hey! Stop it!",
  "What was that??!!!!",
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
  "Oh boy oh boy oh boy.",
  "Hey {name} play again!",
  "Good night, {name}"
]
