[tool.poetry]
name = "bottle-argsmap"
version = "0.1.1"
description = ""
authors = [ "Cologler <skyoflw@gmail.com>" ]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Cologler/bottle_argsmap-python"

  [tool.poetry.dependencies]
  python = "^3.8"
  bottle = "^0.12.19"
  anyioc = "^0.11.1"

  [tool.poetry.dev-dependencies]
  pytest = "^6.2.4"
  WebTest = "^2.0.35"

[tool.poetry-dynamic-versioning]
enable = false

[build-system]
requires = [ "poetry-core>=1.0.0", "poetry-dynamic-versioning" ]
build-backend = "poetry.core.masonry.api"
