[tool.poetry]
name = "Magic Web"
version = "1.0.0"
description = ""
authors = ["Israel Waldner <imky171@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
WebOb = "^1.8.7"
parse = "^1.19.0"
waitress = "^2.0.0"
jijna2 = "^3.0.1"

[tool.poetry.dev-dependencies]
build = "^0.6.1"
twine = "^3.4.2"
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]