[tool.poetry]
name = "LauncherP"
version = "0.1.7"
description = "A nice way to launch my other projects"
authors = ["PetchouHelper <petchou91d@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Kivy = "^2.0.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
