
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-20T11:26:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "faa101c3b8bbe5f92983b0215c6f44ceaa70883f",
 "version": "0.4.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
