[tool.poetry]
name = "service-bindings"
version = "1.0.0"
description = "A library to access [Service Binding Specification for Kubernetes](https://k8s-service-bindings.github.io/spec/) conformant Service Binding [Workload Projections](https://k8s-service-bindings.github.io/spec/#workload-projection)."
license = "Apache-2.0"
authors = ["Ben Hale <nebhale@nebhale.com>"]
readme = 'README.md'
homepage = "https://github.com/nebhale/client-python"
repository = "https://github.com/nebhale/client-python"

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]

packages = [
  { include = "bindings" }
]

[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.12.1"
flake8 = "^3.9.2"
black = {version = "^21.7b0", allow-prereleases = true}
mypy = "^0.910"
isort = "^5.9.3"
psycopg2 = "^2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
