[tool.poetry]
name = "census2020"
version = "0.1.0"
description = "Some helper functions for working with Census 2020 data"
packages = [
    { include = "census2020", from = "src" }
]
authors = ["Kevin Wilson <khwilson@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/khwilson/Census2020"
repository = "https://github.com/khwilson/Census2020"
keywords = ["census", "pl94", "decennial", "redistricting"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]
include = ["LICENSE.md"]


[tool.poetry.dependencies]
python = "^3.7.1"
requests = "^2.26.0"
us = "^2.0.2"
pyarrow = "^5.0.0"
click = "^8.0.1"
tqdm = "^4.62.1"
StrEnum = "^0.4.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.6.0"
pytest = "^6.2.1"
isort = "^5.7.0"
ipdb = "^0.13.4"
mypy = "^0.910"
pandas = "^1.3.2"
types-requests = "^2.25.6"
importlib-metadata = "^4.6.4"

[tool.poetry.scripts]
census2020 = "census2020.cli:cli"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.basic]
good-names = "i,j,k,ex,Run,_,df,pc"

[tool.pylint.messages_control]
disable = "C0330, C0326, R0912, R0913, R0914, R0915"

[tool.pylint.format]
max-line-length = "88"

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
