[tool.poetry]
name = "ardkit"
version = "0.1.0"
description = "Ardkit, the open source cloud"
authors = ["Ardustri <ardkit@ardustri.org>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
