#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['buildcatrust', 'buildcatrust.tests']

package_data = \
{'': ['*'],
 'buildcatrust': ['.pytest_cache/*',
                  '.pytest_cache/v/*',
                  '.pytest_cache/v/cache/*',
                  'tools/*'],
 'buildcatrust.tests': ['.pytest_cache/*',
                        '.pytest_cache/v/*',
                        '.pytest_cache/v/cache/*',
                        'testdata/*',
                        'testdata/local/*']}

entry_points = \
{'console_scripts': ['buildcatrust = buildcatrust.cli:main']}

setup(name='buildcatrust',
      version='0.1.3',
      description='Utilities for turning one trust store into another.',
      author='Luke Granger-Brown',
      author_email='buildcatrust@lukegb.com',
      url='https://github.com/lukegb/buildcatrust',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
