[tool.poetry]
name = "my_unique_test"
version = "0.6.5"
description = ""
authors = ["Leandro G. Almeida <leandro.g.almeida@gmail.com>"]
license = "Apache-2.0"
include = [
  "src/my_unique_test/*.py",
  "README.md"
]
readme = "README.md"
repository = "https://github.com/lalmei/commit_with_tag_version"
keywords = ["machine learning", "data profiling", "data quality", "data logging"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apple Public Source License",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = ">=3.6.1,<3.10"
bump2version = "^1.0.1"


[tool.poetry.dev-dependencies]
pytest = "6.1.2"
pytest-cov = "^2.11.1"
bump2version = "^1.0.1"
black = "^20.8b1"
setuptools = "^56.0.0"
isort = "^5.8.0"
autoflake = "^1.4"
flake8 = "^3.9.1"
twine = "^3.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
skip = [".venv"]

[tool.black]
line-length = 160
target-version = ["py39"]
include_trailing_comma = "True"
exclude = ""
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
