
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-18T16:35:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c5d5deab51e7dfdc9199be050abac8b67730a3f",
 "version": "0.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
