
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-20T14:02:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "56a681ef7f675a5d2cdddda007e3b4bcde6deb8f",
 "version": "1.26.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
