name: jupytery-auth
channels:
  - defaults
  - conda-forge
  - conda-forge/label/jupyterlab_alpha
dependencies:
  - jupyter-packaging
  - jupyterlab=3.1.0
  - jupyterlab-link-share=0.2
  - nodejs=14.15.1
  - pycurl
  - pip
  - pytest
  - python=3.9
  - twine
  - yarn=1.22.5
  - pip:
    - nbclassic==0.2.6
