
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-19T12:03:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "47e2b92283aaeb52e33f2351afbd051e726ff5c9",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
