
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-19T15:03:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "8981f723e132aa55163ef933779d26752994fc16",
 "version": "v2.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
