[tool.poetry]
name = "Laminos.py"
version = "1.0.1"
description = ""
authors = ["Legionsungert <beginnersbaster@gmail.com"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.scripts]
my-script = "my_package.Laminos:start"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"