[package]
name = "aliyundrive-webdav"
version = "0.1.0"
edition = "2018"
description = "WebDAV server for AliyunDrive"
license = "MIT"
repository = "https://github.com/messense/aliyundrive-webdav.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# actix-web = { version = "4.0.0-beta.6", default-features = false, features = ["compress-gzip"] }
anyhow = "1.0.43"
async-recursion = "0.3.2"
bytes = "1.0.1"
futures = "0.3.16"
headers = "0.3.4"
hyper = { version = "0.14.11", features = ["server"] }
log = "0.4.14"
moka = { version = "0.5.1", features = ["future"] }
percent-encoding = "1.0"
pretty_env_logger = "0.4.0"
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls", "gzip", "deflate"] }
serde = { version = "1.0.127", features = ["derive"] }
structopt = "0.3.22"
time = "0.2.0"
tokio = { version = "1.10.0", features = ["full"] }
webdav-handler = { version = "0.2.0", features = ["hyper"] }

[patch.crates-io]
webdav-handler = { git = "https://github.com/messense/webdav-handler-rs.git", branch = "read-buf-size" }
