[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pillow",
    "discord",
    "asyncio",
    "aiohttp",
    "typing",
    "datetime"
]
build-backend = "setuptools.build_meta"