[project]
name = "nsync-cli"
version = "0.1.0"
description = "NeutronSync command line client. Use to securely sync your dot files."
dependencies = [ "typer~=0.3", "cryptography~=3.4", "httpx[brotli,http2]~=0.18", "py-essentials~=1.4", "pendulum~=2.1",]
requires-python = ">=3.7"
dynamic = [ "classifiers",]
[[project.authors]]
name = "Paul Bailey"
email = "paul@neutron.studio"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[console_scripts]
nsync = "nsync_cli.main:app"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/neutron-sync/nsync-cli"

[project.optional-dependencies]

[tool.pdm.dev-dependencies]
dev = [ "yapf~=0.31",]

[tool.pdm.scripts]
format = "yapf -rpi -vv ."
check_format = "yapf -rpd ."
