
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-27T20:38:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdc93e2b0598d387cca20707815cc300f6389f8f",
 "version": "2.4.0dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
