"""Module version and author info."""
__title__ = "lgloria-mysqltosqlite3"
__description__ = "A simple Python tool to transfer data from MySQL to SQLite 3"
__url__ = "https://github.com/"
__version__ = "1.4.8"
__author__ = "LGloria"
__author_email__ = "teste@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2021 "
