[tool.black]
line-length = 119
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 119
known_first_party = ["liquichain", "app", "tests"]

[tool.pytest.ini_options]
mock_use_standalone_module = true
addopts = """
    --cov liquichain/
    --no-cov-on-fail
    --cov-fail-under=80
    --cov-report=term-missing
    --isort
    --flake8
"""
