
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-27T15:25:32+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a1c0024245fc67df2138456483b9af90d1dc060",
 "version": "1.0.7rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
