# CONFIG FILE

class Config:
    Category_URLS = {
        'Free to Play': 'https://store.steampowered.com/genre/Free%20to%20Play/',
        'Demos': 'https://store.steampowered.com/demos/',
        'Early Access': 'https://store.steampowered.com/genre/Early%20Access/',
        'Controller Friendly': 'https://store.steampowered.com/controller/',
        'Software': 'https://store.steampowered.com/software/',
        'Soundtracks': 'https://store.steampowered.com/soundtracks',
        'VR': 'https://store.steampowered.com/vr/',
        'macOS': 'https://store.steampowered.com/macos',
        'SteamOS': 'https://store.steampowered.com/linux',
        'PC Cafe': 'https://store.steampowered.com/pccafe/',
        'Action': 'https://store.steampowered.com/category/action/',
        'Action Rogue Like': 'https://store.steampowered.com/category/action_rogue_like/',
        'Arcade & Rhythm': 'https://store.steampowered.com/category/arcade_rhythm/?snr=1_241_4_actionroguelike_12',
        'Beat Em Up': 'https://store.steampowered.com/category/action_beat_em_up/',
        'Fighting & Martial Arts': 'https://store.steampowered.com/category/fighting_martial_arts/',
        'First Person Shooter': 'https://store.steampowered.com/category/action_fps/',
        'Platformer & Runner': 'https://store.steampowered.com/category/action_run_jump/',
        'Third Person Shooter': 'https://store.steampowered.com/category/action_tps/',
        'Adventure & Casual': 'https://store.steampowered.com/category/adventure_and_casual/',
        'Adventure': 'https://store.steampowered.com/category/adventure/',
        'Adventure RPG': 'https://store.steampowered.com/category/adventure_rpg/',
        'Casual': 'https://store.steampowered.com/category/casual/',
        'Metroidvania': 'https://store.steampowered.com/category/metroidvania/',
        'Puzzle': 'https://store.steampowered.com/category/puzzle_matching/',
        'Story Rich': 'https://store.steampowered.com/category/interactive_fiction/',
        'Visual Novel': 'https://store.steampowered.com/category/visual_novel/',
        'Role Playing': 'https://store.steampowered.com/category/rpg/',
        'Action RPG': 'https://store.steampowered.com/category/rpg_action/',
        'JRPG': 'https://store.steampowered.com/category/rpg_jrpg/',
        'Party Based': 'https://store.steampowered.com/category/rpg_party_based/',
        'Strategy RPG': 'https://store.steampowered.com/category/rpg_strategy_tactics/',
        'Turn Based RPG': 'https://store.steampowered.com/category/rpg_turn_based/',
        'Simulation': 'https://store.steampowered.com/category/simulation/',
        'Building & Automation': 'https://store.steampowered.com/category/sim_building_automation/',
        'Business & Tycoon': 'https://store.steampowered.com/category/sim_business_tycoon/',
        'Dating': 'https://store.steampowered.com/category/sim_dating/',
        'Farming & Crafting': 'https://store.steampowered.com/category/sim_farming_crafting/',
        'Life & Immersive': 'https://store.steampowered.com/category/sim_life/',
        'Sandbox & Physics': 'https://store.steampowered.com/category/sim_physics_sandbox/',
        'Space & Flight': 'https://store.steampowered.com/category/sim_space_flight/',
        'Strategy': 'https://store.steampowered.com/category/strategy/',
        'Card & Board': 'https://store.steampowered.com/category/strategy_card_board/',
        'City & Settlement': 'https://store.steampowered.com/category/strategy_cities_settlements/',
        'Grand & 4X': 'https://store.steampowered.com/category/strategy_grand_4x/',
        'Military': 'https://store.steampowered.com/category/strategy_military/',
        'Real Time Strategy': 'https://store.steampowered.com/category/strategy_real_time/',
        'Tower Defense': 'https://store.steampowered.com/category/tower_defense/',
        'Turn Based Strategy': 'https://store.steampowered.com/category/strategy_turn_based/',
        'Sports & Racing': 'https://store.steampowered.com/category/sports_and_racing/',
        'Sports': 'https://store.steampowered.com/category/sports/',
        'Fishing & Hunting': 'https://store.steampowered.com/category/sports_fishing_hunting/',
        'Individual Sports': 'https://store.steampowered.com/category/sports_individual/',
        'Racing': 'https://store.steampowered.com/category/racing/',
        'Racing Sim': 'https://store.steampowered.com/category/racing_sim/',
        'Sports Sim': 'https://store.steampowered.com/category/sports_sim/',
        'Team Sports': 'https://store.steampowered.com/category/sports_team/',
        'Anime': 'https://store.steampowered.com/category/anime/',
        'Horror': 'https://store.steampowered.com/category/horror/',
        'Mystery & Detective': 'https://store.steampowered.com/category/mystery_detective/',
        'Open World': 'https://store.steampowered.com/category/exploration_open_world/',
        'Sci-Fi & Cyberpunk': 'https://store.steampowered.com/category/science_fiction/',
        'Space': 'https://store.steampowered.com/category/space/',
        'Survival': 'https://store.steampowered.com/category/survival/',
        'Co-Op': 'https://store.steampowered.com/category/multiplayer_coop/',
        'LAN': 'https://store.steampowered.com/category/multiplayer_lan/',
        'Local & Party': 'https://store.steampowered.com/category/multiplayer_local_party/',
        'MMO': 'https://store.steampowered.com/category/multiplayer_mmo/',
        'Multiplayer': 'https://store.steampowered.com/category/multiplayer/',
        'Online Competitive': 'https://store.steampowered.com/category/multiplayer_online_competitive/',
        'Singleplayer': 'https://store.steampowered.com/category/singleplayer/'
    }
