[tool.poetry]
name = "polyrepo-bt"
version = "0.1.5"
description = "A build tool for poetry packages (living in submodules of a Git repo)"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
packages = [
    { include = "pbt" }
]

[tool.poetry.scripts]
pbt = 'pbt.cli:cli'

[tool.poetry.dependencies]
python = "^3.8"
orjson = "^3.6.3"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
