# Generated by Django 3.1.7 on 2021-08-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('push_limit', models.IntegerField(default=42)),
            ],
            options={
                'db_table': 'django_asyncio_task_queue_config',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.TextField()),
                ('label', models.TextField()),
                ('task_id', models.TextField()),
                ('exc_type', models.TextField()),
                ('exc_value', models.TextField()),
                ('exc_traceback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_asyncio_task_queue_error',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.TextField()),
                ('label', models.TextField()),
                ('task_id', models.TextField()),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_asyncio_task_queue_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('error_count', models.IntegerField(null=True, verbose_name='errors')),
                ('log_count', models.IntegerField(null=True, verbose_name='logs')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'django_asyncio_task_queue_stat',
                'ordering': ('label',),
            },
        ),
    ]
