[tool.poetry]
name = "lgblkb-tools"
version = "2.1.0"
description = "Helper tools for lgblkb)"
authors = ["lgblkb <dbakhtiyarov@nu.edu.kz>"]

[tool.poetry.dependencies]
python = ">=3.8"
numpy = "*"
matplotlib = "*"
more-itertools = "*"
requests = "*"
geojson = "*"
shapely = "*"
python-log-indenter = "*"
wrapt = "*"
colorlog = "*"
python-telegram-bot = "*"
pyproj = "*"
geopandas = "*"
opencv-python = "*"
scipy = "*"
geoalchemy2 = "*"
sqlalchemy = "*"
dynaconf = "*"
pyyaml = "*"
python-box = { extras = ["ruamel.yaml", "toml"], version = "*" }
#bumpversion = "*"
#gitchangelog = "*"
invoke = "*"
pandas = "*"
checksumdir = "*"
ortools = "*"
visilibity = "*"
networkx = "*"
sortedcontainers = "*"
ujson = "^4.1.0"
scikit-learn = "*"

#db = ["geoalchemy2=^0.6.3", "sqlalchemy=^1.3.13"]

[tool.poetry.dev-dependencies]
pytest = "*"
#gitchangelog = "^3.0.4"
#taskipy = "^1.2.1"

#[tool.semantic_release]
#version_variable = "pyproject.toml:{tool.poetry}.version"
#version_variable = "lgblkb_tools/__init__.py:__version__"

#[tool.taskipy.tasks]
#export = "poetry export --without-hashes -f requirements.txt > requirements.txt"
#bump = "poetry version patch"
#install = "poetry run pip install -U lgblkb-tools && poetry run pip install -U lgblkb-tools"
#publish = "poetry update && poetry check && task export && task bump && gitchangelog > ChangeLog && poetry publish --build && task install"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

