[tool.poetry]
name = "cls-client"
version = "0.1.1"
description = ""
authors = ["Dave Gaeddert <dave.gaeddert@dropseed.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
