[tool.poetry]
name = "puck-me"
version = "0.1.2"
description = ""
authors = ["Nathan <nathansaccon10@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
beautifulsoup4 = "^4.9.3"
pandas = "^1.3.1"
lxml = "^4.6.3"
html5lib = "^1.1"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
