name: Update the main tag of the Docker container

on:
  push:
    branches:
      - main

jobs:
  update-docker-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push the main branch as main tag
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache_froms: konstin2/maturin:main
          repository: konstin2/maturin
          tag_with_ref: false
          tags: main
          build_args: BUILDKIT_INLINE_CACHE=1
