#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['phx_events']

package_data = \
{'': ['*']}

setup(name='phx-events',
      version='0.1.2',
      description='AsyncIO Phoenix Channels client that supports running handler functions (coroutines or normal functions)',
      author=None,
      author_email='Jethro Muller <git@jethromuller.co.za>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.9,<4',
     )
