[tool.poetry]
name = "partx"
version = "0.1.0"
description = "PartX Optimizer to use with PSY-Taliro"
authors = ["Aniruddh Chandratre <achand75@asu.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
psy-taliro = "^1.0.0a4"
numpy = "^1.20.3"
scikit-learn = "^0.24.2"
pandas = "^1.2.4"
scipy = "^1.6.3"
matplotlib = "^3.4.2"
bokeh = "^2.3.2"
pathos = "^0.2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
