[tool.poetry]
name = "comic_html_view_generator"
version = "0.1.0"
description = ""
authors = ["Leland Batey <lelandbatey@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^4.1.2"
sphinx-rtd-theme = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
