[tool.poetry]
name = "unpoly"
version = "0.0.1"
description = "Framework agnostic implementation of the unpoly server-protocol."
authors = ["Florian Apolloner <florian@apolloner.eu>"]

[tool.poetry.dependencies]
python = ">=3.6.2,<3.11"
attrs = "^21.2.0"

[tool.poetry.dev-dependencies]
Django = "^3.2.6"
black = "^21.7b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
flake8-bugbear = "^21.4.3"
pytest = "^6.2.4"
bump2version = "^1.0.1"
pytest-cov = "^2.12.1"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
