[tool.poetry]
name = "Magic Web"
version = "0.1.0"
description = ""
authors = ["Israel Waldner <imky171@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
WebOb = "^1.8.7"
parse = "^1.19.0"
waitress = "^2.0.0"


[tool.poetry.dev-dependencies]
build = "^0.6.1"
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
