VERSION_YEAR = 2021
VERSION_MONTH = int('08')
VERSION_DAY = int('26')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('48')
MAJOR_VERSION = 0
MINOR_VERSION = 8
PATCH_VERSION = 202108260848
version_date = '2021/08/26 08:48'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
