from datetime import datetime
from pathlib import Path
from typing import Any, Optional, Union

class SysVarNotFoundError(Exception): ...

def get(key: str, *, default: Optional[Any] = ...) -> str: ...
def get_bool(key: str, **kwargs: dict) -> bool: ...
def get_datetime(key: str, **kwargs: dict) -> datetime: ...
def get_float(key: str, **kwargs: dict) -> float: ...
def get_int(key: str, **kwargs: dict) -> int: ...
def get_json(key: str, **kwargs: dict) -> Union[dict, list]: ...
def get_path(key: str, **kwargs: dict) -> Path: ...
