[tool.poetry]

name = "solvent"
version = "20.08.22" # <year>.<month>.<day>[.post<build>]
description = "Kills off fake grass."
authors = ["Solvent <solvent@example.com>"]
license = "MIT"

[tool.poetry.dependencies]

python = "^3.7"

pomace = "~0.8.16"
# pomace = { path = "../pomace", develop = true }

caffeine = { version = "~0.5", platform = "darwin" }
typer = "~0.3.2"

[tool.poetry.dev-dependencies]

autoflake = "^1.3.1"
black = "=20.8b1"
isort = "=5.8.0"
mypy = "*"

[tool.poetry.scripts]

solvent = "solvent:main"

[build-system]

requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
