
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-26T15:59:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d19b864ef069b5b0e68a44a40fac92bc9fc8ef54",
 "version": "2021.8.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
