[tool.poetry]
name = "sphinxcontrib-revealjs"
version = "0.1-alpha.1"
description = "Build slides with RevealJS."
authors = ["Ashley Trinh <ashley@hackbrightacademy.com>"]
packages = [
  { include = "sphinxcontrib" }
]

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = "^4.1.1"
cssutils = "^2.3.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
sphinx-autobuild = "^2021.3.14"
pytest = "^6.2.4"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
