[tool.poetry]
name = "mtba"
version = "0.1.0"
description = "meituan ba auth"
authors = ["huoyinghui <hyhlinux@163.com>"]
homepage = "https://github.com/pydtools/mtba/"
repository = "https://github.com/pydtools/mtba/"
documentation = "https://github.com/pydtools/mtba/wiki"
include = ["CHANGELOG.md"]
[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/pydtools/mtba/issues"
"github" = "https://github.com/pydtools/mtba/"