name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Check
      run: cargo check
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --bin persia-embedding-sharded-server --bin persia-embedding-sharded-middleware --verbose --release
    - name: Archive package artifacts
      uses: actions/upload-artifact@v2
      with:
        name: persia-binaries
        path: |
          target/release/persia-embedding-sharded-server
          target/release/persia-embedding-sharded-middleware
