
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-25T11:33:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c591208b4b95b991c2930e40f663a7d809c4727",
 "version": "0.7.0.post.dev402"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
