[tool.poetry]
name = "chocs_middleware.parsed_body"
version = "1.0.1"
description = "This middleware changes behaviour of chocs.HttpRequest.parsed_body."
authors = [
    "Dawid Kraczkowski <dawid.kraczkowski@gmail.com>"
]
license = "MIT"
readme = "README.md"
packages = [
  { include = "chocs_middleware" }
]
homepage = "https://github.com/kodemore/chocs-parsed-body"
repository = "https://github.com/kodemore/chocs-parsed-body"
documentation = "https://github.com/kodemore/chocs-parsed-body"

keywords = ["dataclasses", "dataclass", "http-request", "chocs", "http", "middleware"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

# Requirements
[tool.poetry.dependencies]
python = "^3.8"
chocs = "^1.0.0"
chili = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.1.0"
pytest-cov = "^2.5"
pytest-mock = "^1.9"
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.812"
pylint = "^2.7.2"
