# Generated by Django 3.2.6 on 2021-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistatspr',
            name='db_alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
