
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-21T20:00:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5dfd83e7a481d700b2dbafd7cb7d19b251ea662f",
 "version": "0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
