
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-26T10:46:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbaafd6f34e74b558b15696089ff82002e4ab93b",
 "version": "v0.5.0a.post.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
