[tool.poetry]
name = "StackX"
version = "1.0.0"
description = "Stack(*elements)"
authors = ["semenchuk Community <hootuk@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
