
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-25T20:08:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "86ef507e37342d4917f468cdabc35af9e4a7cdd6",
 "version": "1.21.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
