
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-24T19:04:15+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "8f930b59066cb1e90e6ca8fedf6148055a879714",
 "version": "0.2.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
