
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-22T10:51:19-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "211a36e1c02ba3d78541b48ed99580bb0084b88c",
 "version": "0.3.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
