[tool.poetry]
name = "dapodix"
version = "0.4.0"
description = "Alat bantu aplikasi Dapodik kemdikbud"
authors = ["hexatester <hexatester@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hexatester/dapodix"
repository = "https://github.com/hexatester/dapodix"
include = [
    "LICENSE",
    "LISENSI",
    "README.md",
    "README-EN.md",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Topic :: Education",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.dependencies]
python = "^3.7"
openpyxl = "^3.0.7"
click = "^8.0.1"
cachetools = "^4.2.2"
dapodik = "^0.16.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.910"
black = "^21.7b0"
types-cachetools = "^0.1.10"

[tool.poetry.scripts]
dapodix = "dapodix.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
