[tool.black]
line-length = 132
 
[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
strict = true

[tool.poetry]
name = "slides-viewer"
version = "1.0.0"
description = "Viewer for live presentations, based on manim-presentation for now"
license = "GPL-3.0-or-later"
authors = ["Vincent Lafeychine <vincent.lafeychine@gmail.com>"]
maintainers = ["Vincent Lafeychine <vincent.lafeychine@gmail.com>"]
readme = "README.md"
repository = "https://github.com/lafeychine/slides-viewer/"

[tool.poetry.scripts]
slides-viewer = 'slides_viewer.console:main'

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
pyside2 = "5.15.2"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = { version = "^21.7b0", allow-prereleases = true }
isort = "^5.9.3"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
