[tool.poetry]
name = "techmo-client"
version = "0.1.0"
description = ""
authors = ["Marek Radecki <marek.radecki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
setuptools = "50.3.2"
grpcio = "1.38.1"
grpcio-tools = "1.38.1"
google-api-core = "1.27.0"
protobuf = "3.12.2"
gapic-google-cloud-speech-v1 = "0.15.3"
grpc-google-cloud-speech-v1 = "0.8.1"
proto-google-cloud-speech-v1 = "0.15.3"
google-auth = "1.21.1"
google-auth-httplib2 = "0.0.3"
google-cloud-core = "1.0.2"
google-cloud-speech = "1.0.0"
googleapis-common-protos = "1.6.0"
httplib2 = "0.14.0"
oauth2client = "2.0.0"
pydub = "0.23.1"
PyAudio = "0.2.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
