[tool.poetry]
name = "anyd"
version = "0.4.1"
description = "A small framework for building and using custom Unix daemons."
authors = ["Anatolio Nikiforidis <nikiforova693@gmail.com>"]
license = "BSD"
readme = "README.md"
homepage = "https://github.com/anatolio-deb/anyd"
repository = "https://github.com/anatolio-deb/anyd"
keywords = ["ipc", "sockets", "daemon"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.6b0"
isort = "^5.9.1"
pylint = "^2.8.3"
mypy = "^0.910"

[tool.poetry.scripts]
anyd = 'anyd.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
