[tool.poetry]
name = "nislmigrate"
version = "0.0.17"
description = "The tool for migrating SystemLink data."
authors = ["cnunnall <christian.nunnally@ni.com>"]
readme="README.md"
documentation="https://github.com/ni/NI-SystemLink-Migration"
classifiers=[
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.6.8"
argparse = "^1.4.0"
pymongo = "^3.12.0"

[tool.poetry.dev-dependencies]
tox = "^3.24.2"
pytest = "^6.2.4"
pyproject-flake8 = "^0.0.1a2"
testfixtures = "^6.18.1"

[tool.poetry.scripts]
nislmigrate = 'nislmigrate.migration_tool:run_migration_tool'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length=100

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38, py37, py36
isolated_build = True

[testenv]
deps = poetry
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest {posargs}
passenv =
    ProgramW6432
    ProgramData
"""