
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-25T17:03:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bbc8c95413ca207c59bcfbfa238fc41ee55cced",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
