---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-ebs-kirill
  namespace: processing
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
