name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  # For manually triggering it
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: docker://tiangolo/latest-changes:0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: docs/CHANGELOG.md
          template_file: ./.github/workflows/release-notes.jinja2
          latest_changes_header: '## 0.0.1\n\n'
          debug_logs: true
