clients:
  google-chrome-beta: chrome
  jetbrains-pycharm: terminal
  firefox: firefox
  x-terminal-emulator: terminal
  thunderbird: envelope
  jetbrains-idea-ce: edit
  nautilus: folder-open
  clementine: music
  vlc: play
  signal: comment
deliminator: |
default_icon: dot-circle
