[tool.poetry]
name = "kaldigrpc_client"
version = "0.1.0"
description = ""
authors = ["Giorgos Paraskevopoulos <geopar@central.ntua.gr>"]

[tool.poetry.dependencies]
python = "^3.8"
grpcio = "^1.39.0"
grpcio-tools = "^1.39.0"
pydub = "^0.25.1"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
mypy = "^0.910"

[tool.poetry.scripts]
kaldigrpc-transcribe = 'kaldigrpc_client.client:transcribe_wav'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
