# Note sdk_bundle .toml file - which is how we build the final package.
[tool.poetry]
name = "classiq"
version = "0.1.0"
description = "Classiq SDK Package"
authors = ["Classiq Technologies <support@classiq.io>"]
readme = "README.md"
license = "Proprietary"
homepage = "https://classiq.io"
documentation = "https://classiquantum.com/reference/"
keywords = [
    "quantum",
    "sdk",
    "QAD",
    "QDL",
    "circuit"
]
classifiers = [
    "Environment :: Console",
    "License :: Other/Proprietary License",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering"
]

[tool.poetry.dependencies]
python = "^3.8"
ConfigArgParse = "^1.5"
pydantic = "^1.8.2"
keyring = "^23.0.1"
websockets = "^9.1"
Pyomo = "^6.0.1"
httpx = "^0.18.2"
qiskit = "^0.29.0"
numpy = "^1.20.1"
networkx = "^2.5.1"
more-itertools = "^8.7.0"
# TODO: Uncomment
# This is meant to allow installing classiq_interface (and it's dependencies) once a client installs classiq.
#classiq_interface = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-timeout = "^1.4.2"
pytest-xdist = {extras = ["psutil"], version = "^2.3.0"}
psutil = "^5.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
