[tool.poetry]
name = "e4l"
version = "0.1.4"
description = "enum4linux-ng but pip installable"
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage = "https://github.com/4thel00z/e4l"
packages = [
    { include = "e4l" }
]


[tool.poetry.dependencies]
python = "^3.7"
impacket = "^0.9.23"
ldap3 = "^2.9.1"
PyYAML = "^5.4.1"


[tool.poetry.scripts]
e4l = 'e4l.__main__:main'


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
