[tool.poetry]
name = "openbayes-serving"
version = "0.1.17"
description = "Framework for Openbayes Serving"
authors = ["Proton <bwang@openbayes.com>", "Aisensiy <shanchuan@openbayes.com>"]
maintainers = ["Proton <bwang@openbayes.com>", "Aisensiy <shanchuan@openbayes.com>"]
homepage = "https://openbayes.com"
repository = "https://github.com/signcl/python-openbayes-serving"
license = "MIT"
classifiers = [
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: Chinese (Simplified)",
]

[tool.poetry.dependencies]
python = "^3.6"
flask = "*"
msgpack = ">1.0.0"
requests = "*"
pprintpp = "*"
uvicorn = "*"
httptools = "*"
uvloop = "*"
Flask-Cors = "*"
accept-types = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
neovim = "*"

# [[tool.poetry.source]]
# name = "aliyun"
# url = "http://mirrors.aliyun.com/pypi/"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

