
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-26T09:38:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e102d0b1b6de72d0e048500ab4077cccf45802e0",
 "version": "v0.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
