
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-27T12:05:30-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3418930b7a0815682f824087a978116c53f09798",
 "version": "0.8.324"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
