dist: xenial
language: python
services:
  - docker
cache:
  directories:
    - ${HOME}/.cache
    - ${HOME}/cached-deps
    - ${HOME}/gopath/pkg/mod
    - "$(python3 -c 'import site; print(site.USER_BASE)')"
python:
  - "3.6"
  - "3.9"
env:
  global:
    - PATH=$HOME/cached-deps:$PATH
  jobs:
    - PACHYDERM_VERSION=$(jq -r .pachyderm version.json)
jobs:
  include:
    # other tests
    - python: 3.9
      env:
        - TOXENV=lint
        - PACHYDERM_VERSION=$(jq -r .pachyderm version.json)
    - python: 3.9
      env:
        - TOXENV=examples
        - PACHYDERM_VERSION=$(jq -r .pachyderm version.json)
install:
- make ci-install
before_script:
- make ci-setup
script:
- tox
after_script:
- kubectl describe pods
- kubectl logs --previous deployment/pachd

before_cache:
  # Make sure cache dirs have the necessary permissions for Travis to traverse
  # & copy them all elsewhere
  - proto/pachyderm/etc/testing/travis_cache.sh
