# coding: utf-8

"""
    Dockstore API

    This describes the dockstore API, a webservice that manages pairs of Docker images and associated metadata such as CWL documents and Dockerfiles used to build those images. Explore swagger.json for a Swagger 2.0 description of our API and explore openapi.yaml for OpenAPI 3.0 descriptions.  # noqa: E501

    OpenAPI spec version: 1.12.0-alpha.1-SNAPSHOT
    Contact: theglobalalliance@genomicsandhealth.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import jgreenepack
from jgreenepack.api.organizations_api import OrganizationsApi  # noqa: E501
from jgreenepack.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = jgreenepack.api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_or_reject_invitation(self):
        """Test case for accept_or_reject_invitation

        Accept or reject an organization invitation.  # noqa: E501
        """
        pass

    def test_add_collection_aliases(self):
        """Test case for add_collection_aliases

        Add aliases linked to a collection in Dockstore.  # noqa: E501
        """
        pass

    def test_add_entry_to_collection(self):
        """Test case for add_entry_to_collection

        Add an entry to a collection.  # noqa: E501
        """
        pass

    def test_add_organization_aliases(self):
        """Test case for add_organization_aliases

        Add aliases linked to a listing in Dockstore.  # noqa: E501
        """
        pass

    def test_add_user_to_org(self):
        """Test case for add_user_to_org

        Add a user role to an organization.  # noqa: E501
        """
        pass

    def test_add_user_to_org_by_username(self):
        """Test case for add_user_to_org_by_username

        Add a user role to an organization.  # noqa: E501
        """
        pass

    def test_approve_organization(self):
        """Test case for approve_organization

        Approve an organization.  # noqa: E501
        """
        pass

    def test_create_collection(self):
        """Test case for create_collection

        Create a collection in the given organization.  # noqa: E501
        """
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Create an organization.  # noqa: E501
        """
        pass

    def test_delete_entry_from_collection(self):
        """Test case for delete_entry_from_collection

        Delete an entry from a collection.  # noqa: E501
        """
        pass

    def test_delete_user_role(self):
        """Test case for delete_user_role

        Remove a user from an organization.  # noqa: E501
        """
        pass

    def test_get_all_organizations(self):
        """Test case for get_all_organizations

        List all organizations.  # noqa: E501
        """
        pass

    def test_get_approved_organizations(self):
        """Test case for get_approved_organizations

        List all available organizations.  # noqa: E501
        """
        pass

    def test_get_collection_by_alias(self):
        """Test case for get_collection_by_alias

        Retrieve a collection by alias.  # noqa: E501
        """
        pass

    def test_get_collection_by_id(self):
        """Test case for get_collection_by_id

        Retrieve a collection by ID.  # noqa: E501
        """
        pass

    def test_get_collection_by_name(self):
        """Test case for get_collection_by_name

        Retrieve a collection by name.  # noqa: E501
        """
        pass

    def test_get_collection_description(self):
        """Test case for get_collection_description

        Retrieve a collection description by organization ID and collection ID.  # noqa: E501
        """
        pass

    def test_get_collections_from_organization(self):
        """Test case for get_collections_from_organization

        Retrieve all collections for an organization.  # noqa: E501
        """
        pass

    def test_get_organization_by_alias(self):
        """Test case for get_organization_by_alias

        Retrieve an organization by alias.  # noqa: E501
        """
        pass

    def test_get_organization_by_id(self):
        """Test case for get_organization_by_id

        Retrieve an organization by ID.  # noqa: E501
        """
        pass

    def test_get_organization_by_name(self):
        """Test case for get_organization_by_name

        Retrieve an organization by name.  # noqa: E501
        """
        pass

    def test_get_organization_description(self):
        """Test case for get_organization_description

        Retrieve an organization description by organization ID.  # noqa: E501
        """
        pass

    def test_get_organization_events(self):
        """Test case for get_organization_events

        Retrieve all events for an organization.  # noqa: E501
        """
        pass

    def test_get_organization_members(self):
        """Test case for get_organization_members

        Retrieve all members for an organization.  # noqa: E501
        """
        pass

    def test_get_starred_users_for_approved_organization(self):
        """Test case for get_starred_users_for_approved_organization

        Return list of users who starred the given approved organization.  # noqa: E501
        """
        pass

    def test_reject_organization(self):
        """Test case for reject_organization

        Reject an organization.  # noqa: E501
        """
        pass

    def test_request_organization_review(self):
        """Test case for request_organization_review

        Re-request an organization approval.  # noqa: E501
        """
        pass

    def test_star_organization(self):
        """Test case for star_organization

        Star an organization.  # noqa: E501
        """
        pass

    def test_update_collection(self):
        """Test case for update_collection

        Update a collection.  # noqa: E501
        """
        pass

    def test_update_collection_description(self):
        """Test case for update_collection_description

        Update a collection's description.  # noqa: E501
        """
        pass

    def test_update_organization(self):
        """Test case for update_organization

        Update an organization.  # noqa: E501
        """
        pass

    def test_update_organization_description(self):
        """Test case for update_organization_description

        Update an organization's description.  # noqa: E501
        """
        pass

    def test_update_user_role(self):
        """Test case for update_user_role

        Update a user role in an organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
