meta:
  enable_mfa: false

project_name: leverage
short_name: le

primary_region: us-east-1
secondary_region: us-west-2

organization:
  accounts:
  - name: management
    email: aws@leverage.com
  - name: security
    email: aws+security@leverage.com
  - name: shared
    email: aws+shared@leverage.com
  organizational_units:
    ##-------------------------------------##
    ## Available organizations policies:
    ## - aws_organizations_policy.default
    ## - aws_organizations_policy.standard
    ##-------------------------------------##
  - name: security
    policy:
    - aws_organizations_policy.default
    accounts:
    - security
  - name: shared
    policy:
    - aws_organizations_policy.standard
    accounts:
    - shared

accounts:
  management:
    groups:
    ##------------------------------------------------------------##
    ## Available groups:
    ## - admins:
    ##   Default policies:
    ##   - "arn:aws:iam::aws:policy/AdministratorAccess"
    ## - finops:
    ##   Default policies:
    ##   - "arn:aws:iam::aws:policy/job-function/Billing"
    ##   - "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess"
    ##------------------------------------------------------------##
    - name: admins
      users:
      - john.doe
      policies:
      - '"arn:aws:iam::aws:policy/AdministratorAccess"'
  security:
    groups:
    ##------------------------------------------------------------##
    ## Available groups:
    ## - admins:
    ##   Default policies:
    ##   - aws_iam_policy.assume_admin_role.arn
    ## - auditors:
    ##   Default policies:
    ##   - aws_iam_policy.assume_auditor_role.arn
    ## - devops:
    ##   Default policies:
    ##   - aws_iam_policy.assume_devops_role.arn
    ## - deploymaster:
    ##   Default policies:
    ##   - aws_iam_policy.assume_deploymaster_role.arn
    ##------------------------------------------------------------##
    - name: devops
      users:
      - john.doe
      policies:
      - aws_iam_policy.assume_devops_role.arn
  shared:
    networks:
    - cidr_block: "172.18.0.0/20"
      availability_zones: [a,b]
      private_subnets:
      - "172.18.0.0/23"
      - "172.18.2.0/23"
      public_subnets:
      - "172.18.6.0/23"
      - "172.18.8.0/23"
