
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-19T23:09:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "32b2b7cfc37263f3ded4b758b88964cd2917042e",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
