
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-24T10:34:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c741158598a41d056b4dbf46f0ec4b2b589e75be",
 "version": "1.6.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
